source 'https://rubygems.org/'

# App Stack
gem 'eventmachine'
gem 'faye'
gem 'oat'
gem 'oj'
gem 'thin'
gem 'sinatra', '~> 1.3'
gem 'sinatra-contrib'
gem 'thin'

# Database Stack
gem 'sequel'
gem 'pg'

# Redis
gem 'hiredis', '~> 0.4'
gem 'redis', '~> 3.0', :require => ['redis/connection/hiredis', 'redis']

group :development do
  gem 'pry'
  gem 'rake', '~> 10.0'
  gem 'minitest', '~> 4.6'
  gem 'rack-test', '~> 0.6'
end
